# Sample Configuration file for the VitaOxiPad
# Refer ReadMe for all available options

# The IP address to bind to
ip = "192.168.0.14"

# The port to listen on
port = 5000

# Path to another configuration file (if needed)
# Touchpad config to use:
# - standart
# - alt_triggers
# - rear_touchpad
# - front_touchpad
config = "standart"

# Polling interval in microseconds
polling_interval = 4000

# Enable or disable debug mode
debug = false
