[package]
name = "vitaoxipad_config"
version = "0.1.0"
edition = "2021"

[dependencies]
config = "0.14.1"
toml = "0.8.20"
home = "0.5.11"
serde = { version = "1.0.217", features = ["derive"] }
color-eyre = "0.6.3"
