[package]
name = "cli"
version = "1.1.1"
edition = "2021"

[dependencies]
argh = "0.1.12"
color-eyre = "0.6.3"
log = "0.4.22"
polling = "2.8.0"
pretty_env_logger = "0.5.0"
chrono = "0.4"
flatbuffers_structs = { version = "0.1.0", path = "../flatbuffers_structs" }
protocol = { version = "0.1.0", path = "../protocol" }
vita_reports = { version = "0.1.0", path = "../vita_reports" }
vita_virtual_device = { version = "0.1.0", path = "../vita_virtual_device" }
serde = { version = "1.0.214", features = ["derive"] }
config = "0.14.1"
toml = "0.8.19"
home = "0.5.9"

[build-dependencies]
build-data = "0.2.1"
