[package]
name = "protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
flatbuffers_structs = { path = "../flatbuffers_structs" }
thiserror = "2.0.3"
vita_reports = { path = "../vita_reports" }
tokio-util = { version = "0.7.12", optional = true, features = ["codec"] }
bytes = { version = "1.8.0", optional = true }

[features]
codec = ["dep:tokio-util", "dep:bytes"]
