[package]
name = "vita_virtual_device"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.38"
vita_reports = { version = "0.1.0", path = "../vita_reports" }

[target.'cfg(target_os = "linux")'.dependencies]
input-linux = "0.6.0"

[target.'cfg(windows)'.dependencies]
vigem-client = "0.1.0"
