name: PS Vita server and Windows MSYS2 client builds

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build_vita_server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install flatc
        run: |
          sudo apt update
          sudo apt install -y make git-core cmake python3
          git clone https://github.com/google/flatbuffers.git
          cd flatbuffers
          cmake -G "Unix Makefiles"
          make -j
          sudo make install
          sudo ldconfig

      - name: Install VitaSDK
        run: |
          echo "VITASDK=/usr/local/vitasdk" >> $GITHUB_ENV
          git clone https://github.com/vitasdk/vdpm
          cd vdpm
          export VITASDK=/usr/local/vitasdk
          export PATH="$VITASDK/bin:$PATH"
          ./bootstrap-vitasdk.sh
          ./install-all.sh
          ./vdpm flatbuffers

      - name: Build VitaPad
        run: |
          cmake -S server -B build -D CMAKE_BUILD_TYPE=Release
          cmake --build build

      - name: Upload VPK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: VitaPad.vpk
          path: build/VitaPad.vpk

  build_windows_client:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: git mingw-w64-ucrt-x86_64-gcc mingw-w64-x86_64-rust mingw-w64-x86_64-flatbuffers make wget cmake

      - name: Install dependencies
        run: |
          pacman -S --noconfirm mingw-w64-x86_64-rust mingw-w64-x86_64-flatbuffers mingw-w64-x86_64-cargo-c make wget cmake

      - name: Build Windows x64 Client
        run: |
          export PATH="${{ steps.msys2.outputs.msys2-location }}/mingw64/bin:${PATH}"
          cd ./client
          cargo build --release --bin cli
          cp ./target/release/cli.exe ./target/release/VitaPad-x64.exe

      - name: Upload Windows x64 binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: VitaPad-x64.exe
          path: ./client/target/release/VitaPad-x64.exe

  create_release:
    needs: [build_vita_server, build_windows_client]
    runs-on: ubuntu-latest
    steps:
      - name: Download VitaPad.vpk artifact
        uses: actions/download-artifact@v4
        with:
          name: VitaPad.vpk
          path: ./release

      - name: Download VitaPad-x64.exe artifact
        uses: actions/download-artifact@v4
        with:
          name: cli.exe
          path: ./release

      - name: Upload development release
        if: ${{ github.event_name != 'pull_request' }}
        uses: softprops/action-gh-release@v2
        with:
          name: Development Build
          tag_name: "latest"
          prerelease: true
          files: |
            ./release/VitaPad.vpk
            ./release/VitaPad-x64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
